# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 944758429641709db56ab9df613f1dd6c89e6d951db3c09dc3250aae4fc5e547fed1e9c98018fb0b4d0296d6d0ea4b097bedc1b531cd75213dfb7469d457773c

test:
  secret_key_base: 3a4fb1d75e6ad7b61d60d3194d0e9cddb3684f9f08342e50d2e2b3eaf11ce4ac9e30966b93a736b3a906e16ec542671700d9af45e9405d86f06c9c3fe554c585

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
